version: "3"

services:
  # Database
  db:
    image: mariadb:latest
    container_name: udooku_wordpress_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    container_name: udooku_wordpress_phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpass
    networks:
      - wpsite
  # Wordpress
  wordpress:
    container_name: udooku_wordpress_wordpress
    depends_on:
      - db
    # build: .
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    # uncomment line if you want to use the entire wordpress local folder instead
    # of having to download a wordpress image for the core files
    # volumes: ["./:/var/www/html"]
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./wp-config.php:/var/www/html/wp-config.php
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootpass
    networks:
      - wpsite
networks:
  wpsite:
    driver: bridge
volumes:
  db_data:
